name: Build Docker Container (AMD64) and Deploy
on:
  workflow_run:
    workflows: ["Tests"]
    branches: [main, develop]
    types: 
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      upstream_branch: ${{ github.event.workflow_run.head_branch }}
    steps:
      - uses: actions/checkout@v5
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PAT }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/parasync/delta-backend:${{ github.event.workflow_run.head_branch }}-amd64

  deploy-dev:
    runs-on: self-hosted
    if: >
      github.event.workflow_run.head_branch == 'develop'
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}
      - name: Setup SSH keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

      - name: Add remote host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.DEPLOY_REMOTE_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Upload docker-compose.yml
        run: |
          scp docker-compose.dev.yml \
            ${{ secrets.DEPLOY_REMOTE_USER }}@${{ secrets.DEPLOY_REMOTE_HOST }}:/home/github/docker-compose.backend.develop.yml

      - name: Deploy container via SSH
        run: |
          ssh ${{ secrets.DEPLOY_REMOTE_USER }}@${{ secrets.DEPLOY_REMOTE_HOST }} << 'EOF'
            set -x
            cd /home/github

            # Pull updated image (no rebuild)
            sudo docker compose -f docker-compose.backend.develop.yml pull

            # Restart using the new image
            sudo docker compose -f docker-compose.backend.develop.yml down
            sudo docker compose -f docker-compose.backend.develop.yml up -d
            exit
          EOF
        env:
          GHCR_USER: ${{ secrets.GHCR_USER }}
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}